version: "3.7"
services:
  app:
    build:
      args:
        user: antonio
        uid: 1000
      context: .
      dockerfile: .docker/Dockerfile
    image: digitalocean.com/php
    container_name: app-videoshop
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: app-db-videoshop
    restart: unless-stopped
    ports:
      - "3304:3306"
    environment:
      MYSQL_DATABASE: "videoshop"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_PASSWORD: "password"
      MYSQL_USER: "videoshop_user"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: app-nginx-videoshop
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
